### ISSUE TITLE
Ab js.controller 6.0.1 ist der Adapter Rot.

### ISSUE THREAD

**Issue by Menne01** [iobroker-community-adapters/ioBroker.fakeroku#55]
Adapter 0.22 läuft nicht mehr.

`host.iobroker | 2024-06-11 12:27:39.486 | error | instance system.adapter.fakeroku.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2024-06-11 12:27:39.486 | error | Caught by controller[0]: Node.js v18.20.3
host.iobroker | 2024-06-11 12:27:39.486 | error | Caught by controller[0]:     at node:internal/main/run_main_module:28:49
host.iobroker | 2024-06-11 12:27:39.486 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
host.iobroker | 2024-06-11 12:27:39.485 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1019:12)
host.iobroker | 2024-06-11 12:27:39.485 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1203:32)
host.iobroker | 2024-06-11 12:27:39.485 | error | Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
host.iobroker | 2024-06-11 12:27:39.485 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1364:14)
host.iobroker | 2024-06-11 12:27:39.484 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.fakeroku/main.js:10:21)
host.iobroker | 2024-06-11 12:27:39.484 | error | Caught by controller[0]: TypeError: utils.Adapter is not a function
host.iobroker | 2024-06-11 12:27:39.484 | error | Caught by controller[0]:                     ^
host.iobroker | 2024-06-11 12:27:39.483 | error | Caught by controller[0]: var adapter = utils.Adapter('fakeroku');
host.iobroker | 2024-06-11 12:27:39.483 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.fakeroku/main.js:10`

**Comment by Menne01** [comment]
....läuft wieder. Danke

**Comment by mcm1957** [comment]
fixed with 2.3.0
